### ISSUE TITLE
Issue with setting up StyleGAN2

### ISSUE THREAD

**Issue by cravisjan97** [harskish/ganspace#14]
I follow all the instructions at [https://github.com/harskish/ganspace/blob/master/SETUP.md](https://github.com/harskish/ganspace/blob/master/SETUP.md). But when I run ```python -c "import torch; import upfirdn2d_op; import fused; print('OK')"```, I get the following error:

```ImportError: /home/csundaram/anaconda3/envs/ganspace/lib/python3.7/site-packages/upfirdn2d-0.0.0-py3.7-linux-x86_64.egg/upfirdn2d_op.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument ```

I am not sure why this occurs. This happens every time I run interactive.py or visualize.py

Any help is appreciated. Thanks!

**Comment by harskish** [comment]
I'm not sure what's causing this, could be a CUDA or gcc version mismatch. If you're using something else than CUDA 10.1, then you might want to remove the intermediate build files and recompile with that version. 

However, I just made the CUDA compilation step optional, so you should also be able to run the project without the StyleGAN2 setup step.
