### ISSUE TITLE
Comparison of edit directions in StyleGAN1

### ISSUE THREAD

**Issue by berylsheep-up** [harskish/ganspace#15]
Hello! Thanks for the excellent work! There are some examples compared with InterfaceGAN in Figure 5 of the paper. But i can not found the corresponding settings in the provided figure_edit_zoo.ipynb which contains the  StyleGAN1 wikiart and bedroom examples except ffhq. If I want to reproduce the result, should I retrained the ganspace models in StyleGAN1 in ffhq?

**Comment by harskish** [comment]
Thanks for the heads up! I had forgotten to upload the missing notebooks when updating the paper on arxiv.
The missing notebooks have been added in commit 1322b290cff53de2d3ba845d91f0be779a9c81a4.
