### ISSUE TITLE
change hair color code

### ISSUE THREAD

**Issue by tom666tom666** [harskish/ganspace#18]
I want to use the method you mentioned in the paper to change the latent vector to modify the hair color of the person in the image, but your code is too complicated, I did not find the implementation code for this part, can you provide a code？  thank you

**Comment by harskish** [comment]
One hair color edit is performed in the teaser, which is generated by the notebook https://github.com/harskish/ganspace/blob/master/notebooks/figure_teaser.ipynb. There are more components that perform other color changes, the best way to find them is to setup the project and run interactive.py, or to use the Colab Notebook (https://colab.research.google.com/github/harskish/ganspace/blob/master/notebooks/Ganspace_colab.ipynb).
