### ISSUE TITLE
missing 'model.py'

### ISSUE THREAD

**Issue by squarevale** [harskish/ganspace#2]
I've followed the install instructions to the letter, but I'm unable to run  interactive.py with any of the examples in the README (stylegan, stylegan2 or biggan)

(NB the notes at the end about StyleGAN2 installation don't work - there is no setup.py in the directory)

the error is:

Traceback (most recent call last):
  File "interactive.py", line 22, in <module>
    from models import get_instrumented_model
  File "/xxx/ganspace/models/__init__.py", line 11, in <module>
    from .wrappers import *
  File "/xxx/ganspace/models/wrappers.py", line 22, in <module>
    from . import stylegan2
  File "/xxx/ganspace/models/stylegan2/__init__.py", line 14, in <module>
    from model import Generator
ModuleNotFoundError: No module named 'model'

can you help?

**Comment by harskish** [comment]
You probably didn't clone the submodules. You can fix this by running `git submodule update --init --recursive`.

Let me know if that fixes is.

**Comment by squarevale** [comment]
ah! thank you - it's looking more promising now!

**Comment by harskish** [comment]
Closing, feel free to reopen in case of further issues.
