### ISSUE TITLE
Question about a new application

### ISSUE THREAD

**Issue by cpatrickalves** [harskish/ganspace#22]
Hi there, 

Thanks for sharing this amazing project.
I am new in Deep Learning, but I want to learn everything I need to finish my project.

I am trying to build a system to perform a specific task: add acne/wrinkles/scars/etc on faces.
So, once I have a good dataset set of face images with acne (for example), can I accomplish this using your project? 

I saw your results with wrinkles, were awesome.
Can you give the directions to perform the same thing with acne?

**Comment by harskish** [comment]
Hi,

If you have access to a dataset of example images, then you'd be better off with supervised methods like [StyleFlow](https://github.com/RameenAbdal/StyleFlow) or [InterFaceGAN](https://github.com/genforce/interfacegan). If you're interested in editing real photos, then there's also the issue of embedding the real image into the generative model - [In-Domain Inversion](https://genforce.github.io/idinvert/) might be helpful for that.

Keep in mind that scars and acne are quite rare features in typical training datasets, and current GANs probably won't be very good at generating them. You might have to perform transfer learning and fine-tune an FFHQ model to better handle those features.

-Erik

**Comment by cpatrickalves** [comment]
Thanks for the tips Erik!
