### ISSUE TITLE
Convert weights conflict

### ISSUE THREAD

**Issue by berylsheep-up** [harskish/ganspace#27]
Hi! When I try to convert weight by [stylegan2-pytorch]((https://github.com/harskish/stylegan2-pytorch)), I found the environment conflict. The method from stylegan2-pytorch is based on cuda10.0/10.1, while the official stylegan2 is not support for tensorflow2.x. Can you tell me the correct environment like the cuda version, tensorflow-gpu version or the tensorflow version? Thanks!

**Comment by harskish** [comment]
Hi @berylsheep-up ,

I've made some changes that should make converting the weights easier. Specifically, the code now supports exporting the weights from a CPU-only PyTorch environment.
Please take a look at https://github.com/harskish/stylegan2-pytorch#convert-weight-from-official-checkpoints and let me know if that works out for you.

-Erik
