### ISSUE TITLE
Stylegan model conversion doesn't work

### ISSUE THREAD

**Issue by basamelatex** [harskish/ganspace#33]
Hi,

I am using a pretrained stylegan trained on ffhq, but the manipulation just shows weird coloring on images (see attached). Any idea why this can happen? Can it be a problem when converting the tf model to pytorch?

Thanks.

![505363059a0fb7811a7310e095dc6d82a5513027](https://user-images.githubusercontent.com/74701475/107429741-4d584000-6b35-11eb-99f4-5126f2e91d93.jpeg)

**Comment by harskish** [comment]
Sorry, I haven't seen errors like this before, so I am unfortunately unable to help with this.
