### ISSUE TITLE
conda env update -f environment.yml --prune --> produces the following error on M1 macOS Big Sur.

### ISSUE THREAD

**Issue by shrewdacumen** [harskish/ganspace#36]
conda env update -f environment.yml --prune
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - cudatoolkit=10.1

And numba -s

__Time Stamp__
Report started (local time)                   : 2021-03-14 19:49:09.014002
UTC start time                                : 2021-03-14 10:49:09.014059
Running time (s)                              : 1.348543

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : westmere
CPU Count                                     : 8
Number of accessible CPUs                     : ?
List of accessible CPUs cores                 : ?
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit aes cmov cx16 cx8 fxsr mmx
                                                pclmul popcnt sahf sse sse2 sse3
                                                sse4.1 sse4.2 ssse3

Memory Total (MB)                             : 16384
Memory Available (MB)                         : 1617

__OS Information__
Platform Name                                 : macOS-10.16-x86_64-i386-64bit
Platform Release                              : 20.3.0
OS Name                                       : Darwin
OS Version                                    : Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101
OS Specific Version                           : 10.16   x86_64
Libc Version                                  : ?

__Python Information__
Python Compiler                               : Clang 10.0.0
Python Implementation                         : CPython
Python Version                                : 3.8.5
Python Locale                                 : en_US.UTF-8

__LLVM Information__
LLVM Version                                  : 10.0.1

__CUDA Information__
CUDA Device Initialized                       : False
CUDA Driver Version                           : ?
CUDA Detect Output:
None
CUDA Librairies Test Output:
None

__ROC information__
ROC Available                                 : False
ROC Toolchains                                : None
HSA Agents Count                              : 0
HSA Agents:
None
HSA Discrete GPUs Count                       : 0
HSA Discrete GPUs                             : None

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: Intel
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda Build                                   : 3.20.5
Conda Env                                     : 4.9.2
Conda Platform                                : osx-64
Conda Python Version                          : 3.8.5.final.0
Conda Root Writable                           : True

__Installed Packages__
ca-certificates           2021.1.19            hecd8cb5_1
certifi                   2020.12.5        py37hecd8cb5_0
libcxx                    10.0.0                        1
libedit                   3.1.20191231         h1de35cc_1
libffi                    3.3                  hb1e8313_2
ncurses                   6.2                  h0a44026_1
openssl                   1.1.1j               h9ed2024_0
pip                       21.0.1           py37hecd8cb5_0
python                    3.7.10               h88f2d9e_0
readline                  8.1                  h9ed2024_0
setuptools                52.0.0           py37hecd8cb5_0
sqlite                    3.33.0               hffcf06c_0
tk                        8.6.10               hb0a8c7a_0
wheel                     0.36.2             pyhd3eb1b0_0
xz                        5.2.5                h1de35cc_0
zlib                      1.2.11               h1de35cc_3

No errors reported.

__Warning log__
Warning (cuda): CUDA driver library cannot be found or no CUDA enabled devices are present.
Exception class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>
Warning (roc): Error initialising ROC: No ROC toolchains found.
Warning (roc): No HSA Agents found, encountered exception when searching: Error at driver init:

HSA is not currently supported on this platform (darwin).

**Comment by harskish** [comment]
The interactive viewer (interactive.py) currently requires CUDA (via pycuda) in order to draw the output images directly from GPU memory with OpenGL. It would be possible to remove the CUDA dependency and instead upload the output images from main memory to OpenGL, but that would require lots of code changes.

The jupyter notebooks should work fine without CUDA. If you're interested in running those, then you can skip the CUDA-related setup steps.
