### ISSUE TITLE
PyCUDA was compiled without GL extension support

### ISSUE THREAD

**Issue by caleb-severn** [harskish/ganspace#43]
I have got PyCuda pip installed, I have cudnn, and cuda installed on my windows computer. But no matter what I do, I cannot get PyCUDA with GL extension support to work?
I have tried 
https://stackoverflow.com/questions/8461505/pycuda-import-pycuda-gl-as-cuda-gl-how-to-find-pycuda-gl
The solution listed there and it does not seem to work for me? Im sorry to ask about two issues, I'm very new to pycuda.

**Comment by caleb-severn** [comment]
I've actually fixed this one. If you are on a windows device, you should pip install pipwin, then use pipwin to install pycuda. And then it installs it correctly.

**Comment by gauravPB** [comment]
Hi @caleb-severn,
 I am using colab and facing the same problem. Is there any solution for that also?
