### ISSUE TITLE
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.

### ISSUE THREAD

**Issue by TopKruZ** [harskish/ganspace#65]
**I have a issue when I run this code**

`python interactive.py --model=StyleGAN2 --class=ffhq --layer=style --use_w -n=1_000_000 -b=10_000`

**it output this**

OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

![image](https://user-images.githubusercontent.com/50898222/197552824-f4c9b8eb-33a2-47fe-8bf8-066536b717b2.png)

Please help me how to fix it.

My Computer
CPU = i7-8700K
RAM = 32 GB
GPU = 1080ti
CUDA Version = 11.0
Microsoft visual studio Version = 2019

**Comment by muraatozbek** [comment]
write this command
```set KMP_DUPLICATE_LIB_OK=TRUE```
and run again
